### ISSUE TITLE
The proxy seems not work

### ISSUE THREAD

**Issue by yduanBioinfo** [acheong08/EdgeGPT-Proxy#1]
After install the Proxy using GO, I try to run this proxy. Then I get the following informations
~/go/bin/EdgeGPT-Proxy
[GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.

[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:   export GIN_MODE=release
 - using code:  gin.SetMode(gin.ReleaseMode)

[GIN-debug] GET    /ping                     --> main.main.func1 (3 handlers)
[GIN-debug] GET    /edgesvc/turing/conversation/create --> main.proxy (3 handlers)
2023/03/24 12:57:06 net.Listen error: listen tcp: lookup x86_64-conda-linux-gnu: Temporary failure in name resolution

**Comment by acheong08** [comment]
It seems your HOST variable got set by the OS. `export HOST=127.0.0.1`

**Comment by yduanBioinfo** [comment]
It works through. And then I realized that I should set a global proxy (VPN) before using EdgeGPT-Proxy. Is that true? 
And would you host a public proxy as mentioned in [https://github.com/acheong08/EdgeGPT/discussions/194](url)? I doubt how long will a public proxy exist before Microsoft bans it.
