### ISSUE TITLE
how to use it  i don't undeerstand

### ISSUE THREAD

**Issue by DreamMaoMao** [acheong08/EdgeGPT-Proxy#3]
Thank you for providing the proxy. I tried running EdgeGPT-Proxy and then running the previous script, but it didn't work. It seems that the traffic is not being directed to the proxy. Then I tried setting the global proxy to the port where EdgeGPT-Proxy is located, and the proxy log for EdgeGPT-Proxy returned a 404.
![image](https://user-images.githubusercontent.com/30348075/227696932-0ec84d3e-f767-43c7-b976-3beadcedfec3.png)

**Comment by DreamMaoMao** [comment]
我的问题  我一直是直接调用pypi模块的  现在直接下载源码 后设置环境变量export BING_PROXY_URL="https://edge.churchless.tech/edgesvc/turing/conversation/create" 就可以用了

**Comment by yduanBioinfo** [comment]
@DreamMaoMao 你是怎么使用的？我没有搞明白。
我运行EdgeGPT-Proxy可以出来：
[GIN-debug] GET    /ping                     --> main.main.func1 (3 handlers)
[GIN-debug] GET    /edgesvc/turing/conversation/create --> main.proxy (3 handlers)
[GIN-debug] OPTIONS /edgesvc/turing/conversation/create --> main.main.func2 (3 handlers)
2023/03/25 23:18:55 488422 127.0.0.1:8080

然后我切换了一个窗口尝试打开EdgeGPT
python3 -m EdgeGPT --cookie-file cookies.json
是应该这么使用吗？

**Comment by yduanBioinfo** [comment]
哦，我检查了一下。我之前一直是用pip安装的，即使更新了，还是没有--proxy和--wss-link这两个选项。
解决方案是使用git clone到本地，然后python setup.py build。新版本即包含这两个选项了。

**Comment by Natural12349978** [comment]
> @DreamMaoMao 你是怎么使用的？我没有搞明白。 我运行EdgeGPT-Proxy可以出来： [GIN-debug] GET /ping --> main.main.func1 (3 handlers) [GIN-debug] GET /edgesvc/turing/conversation/create --> main.proxy (3 handlers) [GIN-debug] OPTIONS /edgesvc/turing/conversation/create --> main.main.func2 (3 handlers) 2023/03/25 23:18:55 488422 127.0.0.1:8080
> 
> 然后我切换了一个窗口尝试打开EdgeGPT python3 -m EdgeGPT --cookie-file cookies.json 是应该这么使用吗？

运行完这个go编译的程序之后，像你一样输入指令，就能回到原来访问bing的那个接口嘛？我也是不知道如何使用它

**Comment by Natural12349978** [comment]
> 好像失效了 用不了了

是这样的。因为cloudflare好像被微软封禁了。但是我尝试把这个代理脚本部署到render上，实际上我并不会用，也出现了问题。我开了个新的issue。你可以过去看一下。是不是要用--proxy把代理的网站参数传进去？具体是什么字段？可能是因为免费的服务带不起来嘛？但是另一个访问new bing的脚本挂到render的代理可用
